<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ComOnly.cs" />
  </ItemGroup>
  <Target Name="CopyFtdiDll" AfterTargets="Build" Condition="Exists('$(SystemRoot)\System32\FTD2XX.dll')">
    <Copy SourceFiles="$(SystemRoot)\System32\FTD2XX.dll" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>
  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>
</Project>
